### ISSUE TITLE
Single API Elements Package

### ISSUE THREAD

**Issue by smizell** [apiaryio/api-elements#17]
Deprecate `minim-parse-result` and `minim-api-description` and have a single `api-elements` package which depends on `minim`, and contains code from the deprecated packages.

**Comment by kylef** [comment]
This has been completed as https://www.npmjs.com/package/api-elements, and https://www.npmjs.com/package/fury. api-elements and Fury are effectively the only two packages you need to be concerned with when using API Elements. Perhaps we can go a step further and the parse/serialise/compose plugins can go directly into the API Elements package.
